### PR TITLE
Update on chmod for the script

### PR DESCRIPTION
**Pull request by vishwassp-hcl-intel**
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@weichou1229 please help review this PR

**Comment by vishwassp-hcl-intel** [comment]
Without the sudo I am not able to identify the `robot`

**Comment by cloudxxx8** [comment]
Is it possible to make the caller of updateme.sh to use sudo?  Then sudo could apply to the internal commands.

**Comment by vishwassp-hcl-intel** [comment]
I have updated the script by removing the sudo from it

**Pull request merged**
