### PR TITLE
Modify configuration structure and add test cases

### LINKED ISSUE #7: Extract run.py to edgex-taf-common
Since run.py extract to taf-common, common.robot need to modify the config and logs path
This change should work after https://github.com/edgexfoundry-holding/edgex-taf-common/issues/4 finished.

### PR DESCRIPTION
**Pull request by weichou1229**
Fix #7 #9 
In this PR, we modify the configuration structure to support configuration profiles and add common test cases, deployment scripts.

### CODE REVIEW

**Comment by weichou1229** [comment]
@ramya-ranganathan We have put all common test cases in TAF/testScenarios folder and still need to implement other test cases. 

I also add [Skipped tag](https://github.com/edgexfoundry-holding/edgex-taf/pull/10/files#diff-5310b721d440cdf0f1c3b4fb9fccc3cbR41) on unimplemented test cases.
```
ServiceOperation_TC0001b - Startup failed (Core Data Service is unavailable)
    [Tags]  Skipped
    [Setup]  Shutdown "Core Data" service and Modify Configuration Service.ConnectRetries = 1 and Restart DS
    Given "Core Data" service is unavailable
    When DS try to startup
    Then DS should log an error after timeout
    And DS should exit
    [Teardown]  Restart EdgeX
```
So please take a look if you have time.

**Comment by cloudxxx8** [comment]
may we merge this PR?

**Comment by cloudxxx8** [comment]
@vishwassp-hcl-intel may we merge this PR?

**Comment by ramya-ranganathan** [comment]
Looks like i don't have access to merge the pull request as well

**Pull request merged**
